language: node_js
node_js:
  - '8'
branches:
  only:
    - master
cache:
  yarn: true
script:
  - git config --global user.name "yagosenhorini"
  - git config --global user.email "yagosenhorini30@gmail.com"
  - echo "machine github.com login yagosenhorini password 7dd138a491008a38ad667960f4caba0702967d17" > ~/.netrc
  - cd website
  - yarn install
  - GIT_USER="yagosenhorini"
  - yarn run publish-gh-pages